version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    depends_on:
      - db
# no worky yet
# expo_ios:
#   build: ./app
#   volumes:
#     - ./app:/app
#   ports:
#     - "19000:19000"
#     - "19001:19001"
#   depends_on:
#     - db
#     - api
