export const RECEIVE_USER = 'RECEIVE_USER'
export const REMOVE_USER = 'REMOVE_USER'

export const RECEIVE_ERRORS = 'RECEIVE_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION'

export const RECEIVE_GOALS = 'RECEIVE_GOALS'

export const NEW_MESSAGE = 'NEW_MESSAGE'
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES'
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES'
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'
